# Generated by Django 6.0 on 2026-01-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_mahsulotlar_bepulyetkazish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_banner', models.ImageField(upload_to='media/')),
                ('nomi', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Mahsulotlar',
        ),
    ]
