# Generated by Django 6.0 on 2026-01-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='nom',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
