# Generated by Django 6.0 on 2026-01-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_movie_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.RemoveField(
            model_name='main_movie',
            name='nomi',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='nom',
        ),
    ]
