# Generated by Django 6.0 on 2026-01-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_main_remove_main_movie_nomi_remove_movie_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='nomii',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='main_movie',
            name='nomi',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='nom',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
