# Generated by Django 6.0 on 2026-01-15 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_main_nomii_main_movie_nomi_movie_nom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Main',
            new_name='Mainn',
        ),
    ]
